apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: |
    A service for testing Backstage functionality. For example, we can trigger errors
    on the sample-service, these are sent to Sentry, then we can view them in the 
    Backstage plugin for Sentry.                    
  annotations:
    github.com/project-slug: erictnilsson/something
    backstage.io/techdocs-ref: github:https://github.com/erictnilsson/something
    something.com: something
spec:
  type: website
  lifecycle: experimental
  owner: erictnilsson    
